/*
 * This file is generated by jOOQ.
 */
package xyz.grazen.rewards.infrastructure.jooq.public_.tables.records;


import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import xyz.grazen.rewards.infrastructure.jooq.public_.tables.ClientRewards;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientRewardsRecord extends UpdatableRecordImpl<ClientRewardsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.client_rewards.client_id</code>.
     */
    public void setClientId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.client_rewards.client_id</code>.
     */
    public UUID getClientId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.client_rewards.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.client_rewards.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.client_rewards.points</code>.
     */
    public void setPoints(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.client_rewards.points</code>.
     */
    public Long getPoints() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.client_rewards.cashback</code>.
     */
    public void setCashback(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.client_rewards.cashback</code>.
     */
    public BigDecimal getCashback() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.client_rewards.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.client_rewards.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRewardsRecord
     */
    public ClientRewardsRecord() {
        super(ClientRewards.CLIENT_REWARDS);
    }

    /**
     * Create a detached, initialised ClientRewardsRecord
     */
    public ClientRewardsRecord(UUID clientId, String email, Long points, BigDecimal cashback, OffsetDateTime createdAt) {
        super(ClientRewards.CLIENT_REWARDS);

        setClientId(clientId);
        setEmail(email);
        setPoints(points);
        setCashback(cashback);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }
}
