services:
  restaurant_db:
    container_name: "restaurant-db"
    image: "postgres:18"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123"
  rewards_db:
    container_name: "rewards-db"
    image: "postgres:18"
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: "123"
