sonar.projectKey = Jose_Grayson_t1
sonar.sources = src/main/java
sonar.exclusions = **/infrastructure/jooq/**
sonar.host.url = https://sonarqube.ingsoftware.lat/
sonar.token = sqa_4e296de25b56b315988b9a9dfd137d2b4f97e7c3

sonar.tests = src/test/java
sonar.test.inclusions = **/*Test*.java
sonar.java.coverage.reportPaths = build/reports/jacoco/test/jacocoTestReport.xml
sonar.java.binaries = build/classes/java/main
