sonar.projectKey = Jose_Grayson_t1
sonar.sources = .
sonar.exclusions = build/*,.gradle/*,bin/*,**/application.properties
sonar.host.url = https://sonarqube.ingsoftware.lat/
sonar.token = sqa_4e296de25b56b315988b9a9dfd137d2b4f97e7c3

sonar.tests = .
sonar.test.inclusions = src/test/java/**/*.java
sonar.java.coverage.reportPaths = coverage.xml

