/*
 * This file is generated by jOOQ.
 */
package xyz.grazen.rewards.infrastructure.jooq.public_.tables;


import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import xyz.grazen.rewards.infrastructure.jooq.public_.Keys;
import xyz.grazen.rewards.infrastructure.jooq.public_.Public;
import xyz.grazen.rewards.infrastructure.jooq.public_.tables.records.ClientRewardsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientRewards extends TableImpl<ClientRewardsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.client_rewards</code>
     */
    public static final ClientRewards CLIENT_REWARDS = new ClientRewards();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClientRewardsRecord> getRecordType() {
        return ClientRewardsRecord.class;
    }

    /**
     * The column <code>public.client_rewards.client_id</code>.
     */
    public final TableField<ClientRewardsRecord, UUID> CLIENT_ID = createField(DSL.name("client_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.client_rewards.email</code>.
     */
    public final TableField<ClientRewardsRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.client_rewards.points</code>.
     */
    public final TableField<ClientRewardsRecord, Long> POINTS = createField(DSL.name("points"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.client_rewards.cashback</code>.
     */
    public final TableField<ClientRewardsRecord, BigDecimal> CASHBACK = createField(DSL.name("cashback"), SQLDataType.NUMERIC.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>public.client_rewards.created_at</code>.
     */
    public final TableField<ClientRewardsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private ClientRewards(Name alias, Table<ClientRewardsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClientRewards(Name alias, Table<ClientRewardsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.client_rewards</code> table reference
     */
    public ClientRewards(String alias) {
        this(DSL.name(alias), CLIENT_REWARDS);
    }

    /**
     * Create an aliased <code>public.client_rewards</code> table reference
     */
    public ClientRewards(Name alias) {
        this(alias, CLIENT_REWARDS);
    }

    /**
     * Create a <code>public.client_rewards</code> table reference
     */
    public ClientRewards() {
        this(DSL.name("client_rewards"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ClientRewardsRecord> getPrimaryKey() {
        return Keys.CLIENT_REWARDS_PKEY;
    }

    @Override
    public ClientRewards as(String alias) {
        return new ClientRewards(DSL.name(alias), this);
    }

    @Override
    public ClientRewards as(Name alias) {
        return new ClientRewards(alias, this);
    }

    @Override
    public ClientRewards as(Table<?> alias) {
        return new ClientRewards(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientRewards rename(String name) {
        return new ClientRewards(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientRewards rename(Name name) {
        return new ClientRewards(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientRewards rename(Table<?> name) {
        return new ClientRewards(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRewards where(Condition condition) {
        return new ClientRewards(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRewards where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRewards where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRewards where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientRewards where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientRewards where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientRewards where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientRewards where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRewards whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRewards whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
