/*
 * This file is generated by jOOQ.
 */
package xyz.grazen.restaurant.infrastructure.jooq.public_.tables.records;


import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import xyz.grazen.restaurant.infrastructure.jooq.public_.tables.Orders;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.orders.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.orders.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.orders.client_id</code>.
     */
    public void setClientId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.orders.client_id</code>.
     */
    public UUID getClientId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.orders.restaurant_code</code>.
     */
    public void setRestaurantCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.orders.restaurant_code</code>.
     */
    public String getRestaurantCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.orders.total</code>.
     */
    public void setTotal(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.orders.total</code>.
     */
    public BigDecimal getTotal() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.orders.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.orders.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(UUID id, UUID clientId, String restaurantCode, BigDecimal total, OffsetDateTime createdAt) {
        super(Orders.ORDERS);

        setId(id);
        setClientId(clientId);
        setRestaurantCode(restaurantCode);
        setTotal(total);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }
}
