spring.application.name = restaurant
server.port = 8080

spring.output.ansi.enabled = ALWAYS

spring.datasource.url = jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username = ${DB_USER}
spring.datasource.password = ${DB_PASSWORD}

springdoc.swagger-ui.enabled = true
springdoc.swagger-ui.path = /docs
springdoc.api-docs.enabled = true
springdoc.api-docs.path = /openapi.json
springdoc.use-bean-validation = true

spring.rabbitmq.addresses = amqp://localhost:5673/
