sonar.sources = src/main/java
sonar.exclusions = **/infrastructure/jooq/**
sonar.tests = src/test/java
sonar.test.inclusions = **/*Test*.java
sonar.java.coverage.reportPaths = build/reports/jacoco/test/jacocoTestReport.xml
sonar.java.binaries = build/classes/java/main
