/*
 * This file is generated by jOOQ.
 */
package xyz.grazen.restaurant.infrastructure.jooq.public_;


import xyz.grazen.restaurant.infrastructure.jooq.public_.tables.Orders;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;
}
