/*
 * This file is generated by jOOQ.
 */
package xyz.grazen.rewards.infrastructure.jooq.public_;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import xyz.grazen.rewards.infrastructure.jooq.public_.tables.ClientRewards;
import xyz.grazen.rewards.infrastructure.jooq.public_.tables.records.ClientRewardsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClientRewardsRecord> CLIENT_REWARDS_PKEY = Internal.createUniqueKey(ClientRewards.CLIENT_REWARDS, DSL.name("client_rewards_pkey"), new TableField[] { ClientRewards.CLIENT_REWARDS.CLIENT_ID }, true);
}
