/*
 * This file is generated by jOOQ.
 */
package xyz.grazen.rewards.infrastructure.jooq.public_;


import xyz.grazen.rewards.infrastructure.jooq.public_.tables.ClientRewards;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.client_rewards</code>.
     */
    public static final ClientRewards CLIENT_REWARDS = ClientRewards.CLIENT_REWARDS;
}
